use crate::{crawler, Index, Result, Root};
use notify::{RecommendedWatcher, RecursiveMode, Watcher};
use std::sync::{mpsc, Arc};
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

#[derive(Clone, Copy)]
enum Message {
    Changed,
    Rebuild,
    Stop,
}
pub struct Service {
    pub index: Arc<Index>,
    sender: mpsc::SyncSender<Message>,
    worker: Option<JoinHandle<()>>,
}
impl Service {
    pub fn start(index: Arc<Index>, roots: Vec<Root>) -> Result<Self> {
        let (sender, receiver) = mpsc::sync_channel(128);
        let events = sender.clone();
        let state = index.clone();
        let worker = thread::Builder::new()
            .name("computer-index".into())
            .spawn(move || {
                #[cfg(target_os = "macos")]
                {
                    extern "C" {
                        fn pthread_set_qos_class_self_np(class: u32, relative_priority: i32)
                            -> i32;
                    }
                    // SAFETY: applies QOS_CLASS_BACKGROUND only to this worker.
                    if unsafe { pthread_set_qos_class_self_np(0x09, 0) } != 0 {
                        state.status.lock().unwrap().warnings.push(
                            "Background QoS unavailable; scan throttling remains enabled".into(),
                        );
                    }
                }
                #[cfg(not(target_os = "macos"))]
                if let Err(error) = thread_priority::set_current_thread_priority(
                    thread_priority::ThreadPriority::Min,
                ) {
                    state
                        .status
                        .lock()
                        .unwrap()
                        .warnings
                        .push(format!("Background priority unavailable: {error}"));
                }
                let event_roots = roots.clone();
                let callback = move |event: notify::Result<notify::Event>| {
                    // Access/read events generated by our own metadata reader do
                    // not request another scan. Hidden/cache changes are ignored.
                    if event.as_ref().map_or(true, |e| {
                        !matches!(e.kind, notify::EventKind::Access(_))
                            && e.paths.iter().any(|p| {
                                event_roots.iter().any(|root| {
                                    p.strip_prefix(&root.path).is_ok_and(|relative| {
                                        relative.components().all(|part| {
                                            crawler::visible(std::path::Path::new(part.as_os_str()))
                                        })
                                    })
                                })
                            })
                    }) {
                        let _ = events.try_send(Message::Changed);
                    }
                };
                let watcher = RecommendedWatcher::new(callback, notify::Config::default());
                let mut watcher = match watcher {
                    Ok(w) => Some(w),
                    Err(e) => {
                        state.status.lock().unwrap().warnings.push(format!(
                            "Watcher unavailable; reconciliation remains active: {e}"
                        ));
                        None
                    }
                };
                if let Some(watcher) = watcher.as_mut() {
                    for root in &roots {
                        if let Err(e) = watcher.watch(&root.path, RecursiveMode::Recursive) {
                            state
                                .status
                                .lock()
                                .unwrap()
                                .warnings
                                .push(format!("Could not watch {}: {e}", root.path.display()));
                        }
                    }
                }
                let _ = state.reconcile(&roots);
                let mut last_scan = Instant::now();
                loop {
                    let mut request = match receiver.recv_timeout(Duration::from_secs(2)) {
                        Ok(request) => request,
                        Err(mpsc::RecvTimeoutError::Disconnected) => break,
                        Err(mpsc::RecvTimeoutError::Timeout) => Message::Changed,
                    };
                    // Coalesce a burst before scanning; never drop Stop/Rebuild.
                    while let Ok(next) = receiver.try_recv() {
                        request = match (request, next) {
                            (Message::Stop, _) | (_, Message::Stop) => Message::Stop,
                            (Message::Rebuild, _) | (_, Message::Rebuild) => Message::Rebuild,
                            _ => Message::Changed,
                        };
                    }
                    match request {
                        Message::Stop => break,
                        Message::Rebuild => {
                            state.pause(false);
                            if let Err(e) = state.rebuild(&roots) {
                                state.status.lock().unwrap().error = Some(e);
                            }
                        }
                        Message::Changed => {
                            // Bound debounce; continuous events cannot starve scans.
                            if last_scan.elapsed() < Duration::from_millis(200) {
                                thread::sleep(Duration::from_millis(200));
                            }
                            let _ = state.reconcile(&roots);
                        }
                    }
                    last_scan = Instant::now();
                }
                drop(watcher);
                let _ = state.checkpoint();
            })
            .map_err(|e| e.to_string())?;
        Ok(Self {
            index,
            sender,
            worker: Some(worker),
        })
    }
    pub fn rebuild(&self) -> Result<()> {
        self.sender
            .try_send(Message::Rebuild)
            .map_err(|e| e.to_string())
    }
}
impl Drop for Service {
    fn drop(&mut self) {
        self.index.pause(true);
        let _ = self.sender.send(Message::Stop);
        if let Some(worker) = self.worker.take() {
            let _ = worker.join();
        }
    }
}
